### PR TITLE
user storage quickstarts

### PR DESCRIPTION
**Pull request by patriot1burke**

### CODE REVIEW

**Comment by stianst** [comment]
This should go into the 7.1.x branch, not 7.0.x branch. It should use the BOM rather than keycloak-parent (https://github.com/redhat-developer/redhat-sso-quickstarts/blob/7.1.x/app-profile-jee-jsp/pom.xml#L49 https://github.com/redhat-developer/redhat-sso-quickstarts/blob/7.1.x/app-profile-jee-jsp/pom.xml#L108).

**Comment by patriot1burke** [comment]
We've already discussed this.  The new user storage quickstarts were going to be based off of community and the product team were going to update the poms when 7.1 builds and maven repo were ready.  These quickstarts will not work against 7.0 beta.

Sorry for committing to 7.0.x.  I thought i was working from master.

**Comment by stianst** [comment]
What are you doing up now? Is it not the middle of the night for you?

I thought we agreed that you'd use 7.1 beta which includes the user storage SPI. I can ask Martin (the single guy on our product team) if he has time to do it for you.

**Comment by bdaw** [comment]
Bill, could you also do the product part aligning with Beta?

**Comment by patriot1burke** [comment]
I'll double check, but I don't think the examples will compile with 7.1 beta as they are based on 2.4.0.  We've discussed this already, but that was weeks ago before the holidays made us forget.  I'll check to see if this is true or not.

**Pull request closed without merging**
