### PR TITLE
fixed client-import.json

### PR DESCRIPTION
**Pull request by hodrigohamalho**
Simple fix updating resource attribute to clientId in client-import.json

### CODE REVIEW

**Comment by stianst** [comment]
Thanks. Could you send the PR to https://github.com/keycloak/keycloak-quickstarts? The RH-SSO quickstarts are actually generated from the Keycloak quickstarts so any changes here would just get overwritten.

**Comment by hodrigohamalho** [comment]
@stianst https://github.com/hodrigohamalho/keycloak-quickstarts/commit/cb033862010a0c400524b9454de1c409acd23ad6 it is already fixed in the master of keycloak, I think you could accept this PR now, and when it be overwrite by keycloak quickstarts everything will still ok.

**Review by pdrozd — APPROVED** [review]

**Comment by stianst** [comment]
ah, sorry I missed that this was going to 7.1.x

**Comment by stianst** [comment]
Thanks

**Pull request merged**
