### PR TITLE
CLOUD-3401 move SSO quickstarts to java 1.8

### PR DESCRIPTION
**Pull request by luck3y**
https://issues.jboss.org/browse/CLOUD-3401
Signed-off-by: Ken Wills <kwills@redhat.com>

### CODE REVIEW

**Comment by luck3y** [comment]
@stianst Is this something we can arrange to have merged? If we don't want to actually change 7.0.x-ose, we could make a 7.0.x-ose-1 branch or something. Its doubtful anyone is still trying to use 1.5 on OS anyway.

Basically I just need to reference a branch that will compile and work with java 11+.

@iankko FYI

**Review by stianst — APPROVED** [review]

**Comment by stianst** [comment]
LGTM, but somehow no-one in the RH-SSO team has write access to this repo anymore.

**Comment by stianst** [comment]
Will try to chase that and merge when I have write access sorted.

**Comment by luck3y** [comment]
Great thanks @stianst!

**Pull request merged**
